# PostgreSQL. Versions 8.2 and up are supported.
development:
  adapter: postgresql
  encoding: unicode
  database: teebox_api_development
  pool: 5
  username: andrew
  password: 
  port: 5432      
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: teebox_api_test
  pool: 5
  username: andrew
  password:
  port: 5432      
  host: localhost
  min_messages: error
      
production:
  adapter: postgresql
  encoding: unicode
  database: teebox_api_production
  pool: 5
  username: 
  password: 
  port: 5432
  host: localhost
